BEGIN;

INSERT INTO events (
  slug,
  title_uz,
  title_de,
  excerpt_uz,
  excerpt_de,
  description_uz,
  description_de,
  category,
  format,
  event_status,
  start_date,
  end_date,
  start_time,
  end_time,
  timezone,
  city,
  bundesland,
  venue_name,
  address,
  online_url,
  organizer_type,
  organizer_name,
  organizer_url,
  registration_status,
  registration_method,
  registration_url,
  registration_value,
  registration_required,
  registration_deadline,
  capacity,
  languages,
  price_label_uz,
  price_label_de,
  official_source_name,
  official_source_url,
  verified_at,
  important_notes_uz,
  important_notes_de,
  status,
  featured
)
VALUES
  (
    'ramazon-hayiti',
    'Ramazon hayiti',
    'Ramadanfest',
    'Germaniyadagi vatandoshlar uchun Ramazon hayiti uchrashuvi konsepti. Sana va manzil tasdiqlangach e’lon yangilanadi.',
    'Konzept für ein gemeinschaftliches Ramadanfest in Deutschland. Datum und Ort werden ergänzt, sobald sie bestätigt sind.',
    ARRAY[
      'Ramazon hayiti munosabati bilan vatandoshlarni bir joyga jamlaydigan iliq va oilaviy uchrashuv konsepti.',
      'Dastur, sana, manzil va qatnashish tartibi tasdiqlangandan keyin shu e’londa yangilanadi.'
    ],
    ARRAY[
      'Konzept für ein warmes, familienfreundliches Treffen zum Ramadanfest für die usbekische Community in Deutschland.',
      'Programm, Datum, Ort und Teilnahmeinformationen werden nach der Bestätigung in dieser Ankündigung ergänzt.'
    ],
    'culture',
    'offline',
    'planning',
    NULL,
    NULL,
    NULL,
    NULL,
    'Europe/Berlin',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'vatandoshlar',
    'Vatandoshlar.de',
    NULL,
    'not_required',
    'none',
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    ARRAY['uz', 'de'],
    'Narx keyinroq e’lon qilinadi',
    'Preis wird später bekannt gegeben',
    NULL,
    NULL,
    NULL,
    ARRAY[
      'Bu rejalashtirilayotgan konsept tadbir — hali tasdiqlangan real tadbir emas.',
      'Aniq sana, joy va ro‘yxatdan o‘tish ma’lumotlari uydirilmaydi; faqat tasdiqlangandan keyin qo‘shiladi.'
    ],
    ARRAY[
      'Dies ist eine Veranstaltung in Planung und noch keine bestätigte reale Veranstaltung.',
      'Datum, Ort und Anmeldung werden nicht vorweggenommen, sondern erst nach Bestätigung ergänzt.'
    ],
    'published',
    FALSE
  ),
  (
    'qurbon-hayiti',
    'Qurbon hayiti',
    'Opferfest',
    'Qurbon hayiti munosabati bilan hamjamiyat uchrashuvi konsepti. Tafsilotlar tasdiqlangach e’lon qilinadi.',
    'Konzept für ein gemeinschaftliches Treffen zum Opferfest. Details werden nach ihrer Bestätigung veröffentlicht.',
    ARRAY[
      'Qurbon hayiti kunlarida vatandoshlar, oilalar va do‘stlarni birlashtiradigan jamoaviy uchrashuv konsepti.',
      'Tadbir formati va amaliy tafsilotlar tayyor bo‘lgach shu sahifada ochiq ko‘rsatiladi.'
    ],
    ARRAY[
      'Konzept für ein gemeinschaftliches Treffen zum Opferfest für Landsleute, Familien und Freunde.',
      'Format und praktische Details werden transparent ergänzt, sobald sie feststehen.'
    ],
    'culture',
    'offline',
    'planning',
    NULL,
    NULL,
    NULL,
    NULL,
    'Europe/Berlin',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'vatandoshlar',
    'Vatandoshlar.de',
    NULL,
    'not_required',
    'none',
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    ARRAY['uz', 'de'],
    'Narx keyinroq e’lon qilinadi',
    'Preis wird später bekannt gegeben',
    NULL,
    NULL,
    NULL,
    ARRAY[
      'Bu rejalashtirilayotgan konsept tadbir — hali tasdiqlangan real tadbir emas.',
      'Sana, manzil va qatnashish tartibi tasdiqlangach yangilanadi.'
    ],
    ARRAY[
      'Dies ist eine Veranstaltung in Planung und noch keine bestätigte reale Veranstaltung.',
      'Datum, Ort und Teilnahme werden nach der Bestätigung ergänzt.'
    ],
    'published',
    FALSE
  ),
  (
    'mustaqillik-bayrami',
    'Mustaqillik bayrami',
    'Unabhängigkeitstag',
    'O‘zbekiston Mustaqillik bayramiga bag‘ishlangan madaniy hamjamiyat tadbiri konsepti.',
    'Konzept für eine kulturelle Community-Veranstaltung zum Unabhängigkeitstag Usbekistans.',
    ARRAY[
      'O‘zbekiston madaniyati, musiqa, an’analar va hamjamiyat ruhini birlashtiradigan bayram tadbiri konsepti.',
      'Aniq dastur va tashkiliy ma’lumotlar tasdiqlangandan keyin e’lon yangilanadi.'
    ],
    ARRAY[
      'Konzept für eine Feier, die usbekische Kultur, Musik, Traditionen und Gemeinschaft miteinander verbindet.',
      'Das konkrete Programm und organisatorische Angaben werden nach ihrer Bestätigung ergänzt.'
    ],
    'culture',
    'offline',
    'planning',
    NULL,
    NULL,
    NULL,
    NULL,
    'Europe/Berlin',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'vatandoshlar',
    'Vatandoshlar.de',
    NULL,
    'not_required',
    'none',
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    ARRAY['uz', 'de'],
    'Narx keyinroq e’lon qilinadi',
    'Preis wird später bekannt gegeben',
    NULL,
    NULL,
    NULL,
    ARRAY[
      'Bu rejalashtirilayotgan konsept tadbir — hali tasdiqlangan real tadbir emas.',
      'Aniq sana va joy faqat rasmiy tasdiqdan keyin ko‘rsatiladi.'
    ],
    ARRAY[
      'Dies ist eine Veranstaltung in Planung und noch keine bestätigte reale Veranstaltung.',
      'Ein konkretes Datum und ein Ort werden erst nach offizieller Bestätigung angegeben.'
    ],
    'published',
    FALSE
  ),
  (
    'vatandoshlar-uchrashuvi',
    'Vatandoshlar uchrashuvi',
    'Treffen der Community',
    'Germaniyada yashayotgan vatandoshlar uchun tanishuv, muloqot va tajriba almashish uchrashuvi konsepti.',
    'Konzept für ein Community-Treffen zum Kennenlernen, Austauschen und Vernetzen in Deutschland.',
    ARRAY[
      'Yangi tanishuvlar, foydali suhbatlar va turli shaharlardagi vatandoshlar o‘rtasida aloqa yaratishga qaratilgan uchrashuv konsepti.',
      'Sana, shahar va format hamjamiyat ehtiyoji va tashkiliy imkoniyatlarga qarab tasdiqlanadi.'
    ],
    ARRAY[
      'Konzept für ein Treffen, das neue Kontakte, hilfreiche Gespräche und die Vernetzung von Landsleuten aus verschiedenen Städten fördert.',
      'Datum, Stadt und Format werden entsprechend dem Bedarf der Community und den organisatorischen Möglichkeiten festgelegt.'
    ],
    'community',
    'offline',
    'planning',
    NULL,
    NULL,
    NULL,
    NULL,
    'Europe/Berlin',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'vatandoshlar',
    'Vatandoshlar.de',
    NULL,
    'not_required',
    'none',
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    ARRAY['uz', 'de'],
    'Narx keyinroq e’lon qilinadi',
    'Preis wird später bekannt gegeben',
    NULL,
    NULL,
    NULL,
    ARRAY[
      'Bu rejalashtirilayotgan konsept tadbir — hali tasdiqlangan real tadbir emas.',
      'Uchrashuv joyi va qatnashish tartibi tasdiqlangach e’lon qilinadi.'
    ],
    ARRAY[
      'Dies ist eine Veranstaltung in Planung und noch keine bestätigte reale Veranstaltung.',
      'Ort und Teilnahmeinformationen werden nach der Bestätigung veröffentlicht.'
    ],
    'published',
    FALSE
  ),
  (
    'sport-turniri',
    'Sport turniri',
    'Sportturnier',
    'Futbol, voleybol, shaxmat va boshqa yo‘nalishlarni birlashtirishi mumkin bo‘lgan hamjamiyat sport turniri konsepti.',
    'Konzept für ein Community-Sportturnier, das Fußball, Volleyball, Schach und weitere Disziplinen verbinden kann.',
    ARRAY[
      'Faol dam olish, jamoaviy ruh va vatandoshlar o‘rtasidagi aloqani kuchaytirishga qaratilgan sport tadbiri konsepti.',
      'Sport turlari, jamoalar formati, sana va joy tashkiliy reja tasdiqlangach yangilanadi.'
    ],
    ARRAY[
      'Konzept für eine Sportveranstaltung, die Bewegung, Teamgeist und die Verbindung innerhalb der Community stärkt.',
      'Disziplinen, Teamformat, Datum und Ort werden ergänzt, sobald die organisatorische Planung bestätigt ist.'
    ],
    'sport',
    'offline',
    'planning',
    NULL,
    NULL,
    NULL,
    NULL,
    'Europe/Berlin',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'vatandoshlar',
    'Vatandoshlar.de',
    NULL,
    'not_required',
    'none',
    NULL,
    NULL,
    FALSE,
    NULL,
    NULL,
    ARRAY['uz', 'de'],
    'Narx keyinroq e’lon qilinadi',
    'Preis wird später bekannt gegeben',
    NULL,
    NULL,
    NULL,
    ARRAY[
      'Bu rejalashtirilayotgan konsept tadbir — hali tasdiqlangan real tadbir emas.',
      'Aniq sport turlari, sana, joy va ro‘yxatdan o‘tish tartibi keyinroq e’lon qilinadi.'
    ],
    ARRAY[
      'Dies ist eine Veranstaltung in Planung und noch keine bestätigte reale Veranstaltung.',
      'Disziplinen, Datum, Ort und Anmeldung werden später bekannt gegeben.'
    ],
    'published',
    FALSE
  )
ON CONFLICT (slug) DO NOTHING;

COMMIT;
